"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username(white)\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$line_break$character"""

palette = 'catppuccin_frappe'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[os]
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
format = '[ $user ]($style)'

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[$symbol $branch]($style)'

[git_status]
format = '[ $all_status$ahead_behind]($style)'

[nodejs]
symbol = ""
format = '[ $symbol( $version)]($style)'

[c]
symbol = " "
format = '[ $symbol( $version)]($style)'

[rust]
symbol = ""
format = '[ $symbol( $version)]($style)'

[golang]
symbol = ""
format = '[ $symbol( $version)]($style)'

[php]
symbol = ""
format = '[ $symbol( $version)]($style)'

[java]
symbol = ""
format = '[ $symbol( $version)]($style)'

[kotlin]
symbol = ""
format = '[ $symbol( $version)]($style)'


[haskell]
symbol = ""
format = '[ $symbol( $version)]($style)'

[python]
symbol = ""
format = '[ $symbol( $version)]($style)'

[docker_context]
symbol = ""
format = '[ $symbol( $context)]($style)'

[conda]
format = '[ $symbol( $environment)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
